version: '3'

services:
  #mariadb
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception
    restart: unless-stopped
    env_file: .env
  #wordpress
  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html/wordpress
    expose:
      - "9000"
    networks:
      - inception
    env_file: .env
  #nginx
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html/wordpress
    ports:
      - "443:443"
    networks:
      - inception
    env_file: .env
 
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/bguillau/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/bguillau/data/wordpress'

networks:
  inception:
    name: inception
